### ISSUE TITLE
Review overflow handling for RAPL counters

### ISSUE THREAD

**Issue by TomTheBear** [rrze-likwid/likwid#13]
In some cases the overflow recognition for the RAPL counters does not work. See https://groups.google.com/forum/#!topic/likwid-users/z2CYJGmqOv8

**Comment by vihanpandey** [comment]
@TomTheBear I was just going to post this, but I'm happy you did it first :-)

**Comment by TomTheBear** [comment]
After some tests, this should be fixed in https://github.com/rrze-likwid/likwid/commit/d5581ffe1859fa5a5becdbecb880d147955879e7 , https://github.com/rrze-likwid/likwid/commit/b9e80985b144bd91a4bb459599455e94573dcd16 and https://github.com/rrze-likwid/likwid/commit/8b978576c9b2c9ad2bfe7fa45c2e7715173aa80e
