### ISSUE TITLE
‘dev’ undeclared

### ISSUE THREAD

**Issue by psteinb** [rrze-likwid/likwid#14]
just compiled master to check on new features, but received this upon a call to "make":
```
$ make
===>  COMPILE  GCC/perfmon.o
In file included from ./src/perfmon.c:60:0:
./src/includes/perfmon_haswell.h: In function ‘perfmon_setupCounterThread_haswell’:
./src/includes/perfmon_haswell.h:1002:43: error: ‘dev’ undeclared (first use in this function)
                  if (haveLock && HPMcheck(dev, cpu_id))
                                           ^
./src/includes/perfmon_haswell.h:1002:43: note: each undeclared identifier is reported only once for each function it appears in
Makefile:174: recipe for target 'GCC/perfmon.o' failed
make: *** [GCC/perfmon.o] Error 1
```

I am using 12dd580d16768c809757f84bf68e5abb064db8cb on fc21 with default gcc. looks to me that something along the lines of
```
PciDeviceIndex dev = counter_map[index].device; 
```
is missing here: https://github.com/rrze-likwid/likwid/blob/master/src/includes/perfmon_haswell.h#L917

**Comment by TomTheBear** [comment]
Hi,

I fixed it in commit https://github.com/rrze-likwid/likwid/commit/583687c04f496dcb89f816c89a28b24c2e73f2ca

Greetings,
Thomas

**Comment by psteinb** [comment]
thanks a bunch
