### ISSUE TITLE
Provide Java API for markers

### ISSUE THREAD

**Issue by jacek-lewandowski** [rrze-likwid/likwid#15]
Actually, I did it with JNI and it looks like it is working fine. Would you guys consider including it if I created a pull request?

**Comment by TomTheBear** [comment]
Hi,

Java is not one of our target languages but since you already did the work, why not? You can create a pull request and I try to check the code whether all cases are covered by your code and whether I find any problems.

Greetings,
Thomas

**Comment by jlewandowski** [comment]
Hi @TomTheBear,
Thanks for reply. For now I pushed it to my repository as a separate project. You may have a look if you have minute. Once I find some time, I'll create a pull request. Just a question - which directory in your project is a right place to put it?

Thank you,
Jacek

**Comment by TomTheBear** [comment]
Hi Jacek,

we talked about it again in the team. We mainly have the problem that nobody in the team is using Java. Although the Marker API are only a few calls, it's hard for us to maintain the interface properly.

If you would maintain the API, it would be the best for us. Based on my quick view on your code, I think you know what you are doing. Would it be a problem for you to keep it in your stock. I would add it to LIKWID's readme file to point interested users to your repo.

Greetings,
Thomas

**Comment by jlewandowski** [comment]
That would work for me as well. It would be very nice if you add that info to you readme file.

Thank you,
Jacek

**Comment by TomTheBear** [comment]
Thanks for your effort. I added the link to the readme file and added a section to the Marker API description in the Wiki for other programming languages.

Greetings,
Thomas
