### ISSUE TITLE
Failure in building likwid-4.0.0 on Sabayon linux

### ISSUE THREAD

**Issue by CaptainSifff** [rrze-likwid/likwid#7]
likwid-4.0.0 fails to build on linux. The failure happens in likwid-bench, see the end of this post.
This happens with gcc-4.8.4 and gcc-4.9.2. I use binutils-2.23.1 
I did not modify the likwid configuration config.mk.
Please feel free to ask if you need any further information.

===>  COMPILE C GCC/strUtil.o
===>  COMPILE C GCC/threads.o
===>  COMPILE C GCC/barrier.o
===>  COMPILE C GCC/allocator.o
===>  COMPILE C GCC/bench.o
===>  GENERATE BENCHMARKS
===>  ASSEMBLE  GCC/vtriad_mem_avx.o
===>  ASSEMBLE  GCC/store_sse.o
===>  ASSEMBLE  GCC/striad_plain.o
===>  ASSEMBLE  GCC/sum_plain.o
===>  ASSEMBLE  GCC/vtriad_avx.o
===>  ASSEMBLE  GCC/copy_mem.o
===>  ASSEMBLE  GCC/copy_mem_avx.o
===>  ASSEMBLE  GCC/clstore.o
===>  ASSEMBLE  GCC/stream.o
===>  ASSEMBLE  GCC/stream_avx.o
===>  ASSEMBLE  GCC/update_plain.o
===>  ASSEMBLE  GCC/sum.o
===>  ASSEMBLE  GCC/vtriad_sse.o
===>  ASSEMBLE  GCC/striad_mem_avx.o
===>  ASSEMBLE  GCC/copy_mem_sse.o
===>  ASSEMBLE  GCC/striad_mem_sse.o
===>  ASSEMBLE  GCC/stream_mem.o
===>  ASSEMBLE  GCC/copy.o
===>  ASSEMBLE  GCC/load.o
===>  ASSEMBLE  GCC/copy_avx.o
===>  ASSEMBLE  GCC/load_avx.o
===>  ASSEMBLE  GCC/store_plain.o
===>  ASSEMBLE  GCC/load_sse.o
===>  ASSEMBLE  GCC/striad_avx.o
===>  ASSEMBLE  GCC/copy_sse.o
===>  ASSEMBLE  GCC/sum_avx.o
===>  ASSEMBLE  GCC/triad_mem.o
===>  ASSEMBLE  GCC/sum_sse.o
===>  ASSEMBLE  GCC/clcopy.o
===>  ASSEMBLE  GCC/update.o
===>  ASSEMBLE  GCC/store_mem.o
===>  ASSEMBLE  GCC/update_avx.o
===>  ASSEMBLE  GCC/store_mem_avx.o
===>  ASSEMBLE  GCC/vtriad_plain.o
===>  ASSEMBLE  GCC/update_sse.o
===>  ASSEMBLE  GCC/store_mem_sse.o
===>  ASSEMBLE  GCC/triad.o
===>  ASSEMBLE  GCC/triad_avx.o
===>  ASSEMBLE  GCC/clload.o
===>  ASSEMBLE  GCC/triad_split.o
===>  ASSEMBLE  GCC/store.o
===>  ASSEMBLE  GCC/striad_sse.o
===>  ASSEMBLE  GCC/store_avx.o
===>  ASSEMBLE  GCC/copy_plain.o
===>  ASSEMBLE  GCC/load_plain.o
===>  ASSEMBLE  GCC/vtriad_mem_sse.o
===>  LINKING  likwid-bench
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/../../../../x86_64-pc-linux-gnu/bin/ld: ./GCC/striad_sse.o: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
./GCC/striad_sse.o: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:95: recipe for target 'likwid-bench_target' failed
make: *** [likwid-bench_target] Error 1

**Comment by TomTheBear** [comment]
Hi,

can you please send me the linking command of likwid-bench (remove $(Q) in line 101 in bench/Makefile). Just to see whether it is able to link other benchmarks but not the striad_sse one.

I assume the problem is cause by the constants we define in the data section of the assembly files. On my system the benchmarks are assembled and later linked in alphabetical order but then it should already fail at the store benchmarks which use the constants, too.

Have you tried to skip the striad_sse benchmark? E.g. by renaming the source file bench/x86-64/striad_sse.ptt? Maybe it is just that single benchmark that cannot be linked.

Greetings,
Thomas

**Comment by CaptainSifff** [comment]
Hi Thomas,
renaming the stream benchmark gives the same error with a new test:
===>  LINKING  likwid-bench
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/../../../../x86_64-pc-linux-gnu/bin/ld: ./GCC/store_mem.o: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
./GCC/store_mem.o: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:95: recipe for target 'likwid-bench_target' failed

**Comment by CaptainSifff** [comment]
The command that was used is this:
gcc  -O2 -std=c99 -Wno-format -fPIC -fPIC   -DPAGE_ALIGNMENT=4096 -DLIKWID_MONITOR_LOCK -DDEBUGLEV=0 -DVERSION=4 -DRELEASE=0 -DCFGFILE=/etc/likwid.cfg -DINSTALL_PREFIX=/usr/local -DMAX_NUM_THREADS=263 -DMAX_NUM_NODES=64 -DLIBLIKWIDPIN=/usr/local/lib/liblikwidpin.so -DLIKWIDFILTERPATH=/usr/local/share/likwid/filter -DLIKWIDPATH=/usr/local -D_GNU_SOURCE -DCOLOR=BLUE -DHAS_MEMPOLICY -DHAS_SCHEDAFFINITY -DLIKWID_USE_HWLOC -DACCESSDAEMON=/usr/local/sbin/likwid-accessD -DACCESSMODE=1  -I./includes -I./GCC -pthread  -o likwid-bench  likwid-bench.c  ./GCC/copy_mem_avx.o  ./GCC/vtriad_sse.o  ./GCC/striad_sse.o  ./GCC/update.o  ./GCC/store_mem.o  ./GCC/triad.o  ./GCC/vtriad_mem_avx.o  ./GCC/stream_mem.o  ./GCC/load.o  ./GCC/copy.o  ./GCC/store_sse.o  ./GCC/stream.o  ./GCC/update_plain.o  ./GCC/vtriad_mem_sse.o  ./GCC/load_sse.o  ./GCC/update_avx.o  ./GCC/store_mem_avx.o  ./GCC/triad_avx.o  ./GCC/copy_plain.o  ./GCC/striad_plain.o  ./GCC/copy_avx.o  ./GCC/sum_sse.o  ./GCC/vtriad_plain.o  ./GCC/store.o  ./GCC/vtriad_avx.o  ./GCC/stream_avx.o  ./GCC/copy_mem_sse.o  ./GCC/clload.o  ./GCC/striad_mem_sse.o  ./GCC/striad_avx.o  ./GCC/triad_split.o  ./GCC/clstore.o  ./GCC/store_plain.o  ./GCC/triad_mem.o  ./GCC/striad_mem_avx.o  ./GCC/store_avx.o  ./GCC/load_plain.o  ./GCC/copy_mem.o  ./GCC/load_avx.o  ./GCC/update_sse.o  ./GCC/store_mem_sse.o  ./GCC/sum_plain.o  ./GCC/sum.o  ./GCC/copy_sse.o  ./GCC/sum_avx.o  ./GCC/clcopy.o  ./GCC/strUtil.o  ./GCC/threads.o  ./GCC/barrier.o  ./GCC/allocator.o  ./GCC/bench.o ../liblikwid.a ../ext/hwloc/libhwloc.a -lm
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/../../../../x86_64-pc-linux-gnu/bin/ld: ./GCC/striad_sse.o: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
./GCC/striad_sse.o: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
Thanks for your help,
Flo.

**Comment by TomTheBear** [comment]
Hi,

I tried GCC 4.9.2 and binutils 2.23.1 on my Ubuntu system and it built without problems. Are you sure that your environment does not define something that could cause the problems? As far as I know, Sabayon is Gentoo based and Gentoo uses a global make.conf to configure the compile process. Does Sabayon use it, too?

You are the first one having problems building likwid-bench with such a failure. If we cannot reduce the search scope, I won't have the time to fix your issue.

**Comment by CaptainSifff** [comment]
OK, thanks for your time. I will try to find out what the issue is....
For the record, this is the command that works(except for the undefined references of the linker)
gcc  -O2 -std=c99 -fPIC -DPAGE_ALIGNMENT=4096 -DLIKWID_MONITOR_LOCK -DDEBUGLEV=0 -DVERSION=4 -DRELEASE=0 -DCFGFILE=/etc/likwid.cfg -DINSTALL_PREFIX=/usr/local -DMAX_NUM_THREADS=263 -DMAX_NUM_NODES=64 -DLIBLIKWIDPIN=/usr/local/lib/liblikwidpin.so -DLIKWIDFILTERPATH=/usr/local/share/likwid/filter -DLIKWIDPATH=/usr/local -D_GNU_SOURCE -DCOLOR=BLUE -DHAS_MEMPOLICY -DHAS_SCHEDAFFINITY -DLIKWID_USE_HWLOC -DACCESSDAEMON=/usr/local/sbin/likwid-accessD -DACCESSMODE=1  -I./includes -I./GCC -pthread  -o likwid-bench  likwid-bench.c  ./GCC/copy_mem_avx.o  ./GCC/vtriad_sse.o  ./GCC/update.o  ./GCC/triad.o  ./GCC/vtriad_mem_avx.o  ./GCC/load.o  ./GCC/copy.o  ./GCC/update_plain.o  ./GCC/vtriad_mem_sse.o  ./GCC/load_sse.o  ./GCC/update_avx.o  ./GCC/triad_avx.o  ./GCC/copy_plain.o   ./GCC/copy_avx.o  ./GCC/sum_sse.o  ./GCC/vtriad_plain.o  ./GCC/vtriad_avx.o   ./GCC/copy_mem_sse.o  ./GCC/clload.o  ./GCC/triad_split.o ./GCC/triad_mem.o  ./GCC/load_plain.o  ./GCC/copy_mem.o  ./GCC/load_avx.o  ./GCC/update_sse.o  ./GCC/sum_plain.o  ./GCC/sum.o  ./GCC/copy_sse.o  ./GCC/sum_avx.o  ./GCC/clcopy.o  ./GCC/strUtil.o  ./GCC/threads.o  ./GCC/barrier.o  ./GCC/allocator.o  ./GCC/bench.o ../liblikwid.a ../ext/hwloc/libhwloc.a -lm


So it seems the issue is restricted to the store, stream and striad tests.

**Comment by TomTheBear** [comment]
Hi,

I took the time to fix the problem. The scalar values are now addressed relatively. I verified the changes on a Sabayon system installed in a virtual machine.

Fixed at commit 6f62a0f52de625888ab59ffd2c5df7f6e79ed897

Greetings,
Thomas

**Comment by CaptainSifff** [comment]
Thank you very much! Can you elaborate a bit what the issue is/was? 
I compiled likwid (without your patch) on other systems. It works on debian 7.7 with gcc-4.7.2, binutils 2.22
and on another Gentoo system with gcc-4.8.4 and binutils 2.24
Thanks,
Flo.

**Comment by TomTheBear** [comment]
It's nice to hear that it compiles without a problem on different operating systems. I commonly test only one or two.

I'm not a professional regarding assembly but I try:

A common assembly file has different sections like `.text` for code, `.data` for global data and some more. We use predefined constants that can be used in the code, like a vector of integers, vector of doubles and so on. These constants reside in the `.data` section and during the build process, the addresses to the constants are calculated but they are absolute and therefore not relocatable. The addresses have not the form of addresses in higher level languages, they are just offsets from the beginning of the file. In order to relocate the constant symbols, you need to add the address of the symbol to the start address of the `.data` section. This start address is stored in the register `rip`, so all I had to change was `[SCALAR]` to `[rip+SCALAR]`.

If you want more information about this topic, I recommend the webpage http://www.mindfruit.co.uk/2012/06/relocations-relocations.html .

Greetings,
Thomas

**Comment by CaptainSifff** [comment]
Thank you very much for this detailed answer!
I learned something new bout the intricacies of linking...
